apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: chat-app-server
  name: chat-app-server
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: chat-app-server
  type: NodePort
status:
  loadBalancer: {}