apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: chat-app-db
  name: chat-app-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: chat-app-db
  type: NodePort
status:
  loadBalancer: {}